# utils.py - Helper functions for repository ingestion

import os
from datetime import timezone
from typing import Iterable, Optional

try:
    from git import Repo
except ImportError:
    Repo = None


SKIP_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
    ".next",
    "coverage",
    "vendor",
    "third_party",
    "target",
    "out",
    ".turbo",
}

SKIP_FILE_NAMES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "cargo.lock",
    "composer.lock",
}

SKIP_SUFFIXES = (
    ".min.js",
    ".min.css",
    ".bundle.js",
    ".generated.js",
    ".generated.ts",
    ".generated.tsx",
    ".g.dart",
    ".pb.go",
    ".designer.cs",
)

GENERATED_MARKERS = (
    "@generated",
    "@auto-generated",
    "auto-generated",
    "autogenerated",
    "generated by",
    "do not edit",
)

MAX_FILE_BYTES = 1_500_000


def clone_or_open_repo(repo_url: str, target_dir: str) -> str:
    """Clone a repository from a URL or open an existing local repo."""
    if repo_url.startswith("http"):
        if not Repo:
            raise RuntimeError("GitPython is not installed. Install with: pip install gitpython")
        if os.path.exists(target_dir):
            print("Repo exists, removing for fresh clone.")
            import shutil

            shutil.rmtree(target_dir, ignore_errors=True)
        print(f"Cloning {repo_url} -> {target_dir}")
        os.makedirs(os.path.dirname(target_dir), exist_ok=True)
        Repo.clone_from(repo_url, target_dir)
    else:
        if not os.path.exists(repo_url):
            raise ValueError(f"Local repository path does not exist: {repo_url}")
        target_dir = repo_url
    return os.path.abspath(target_dir)


def should_skip(file_path: str, repo_path: Optional[str] = None, max_file_bytes: int = MAX_FILE_BYTES) -> bool:
    """Return True when a path is low-value or too expensive to ingest."""
    abs_path = os.path.abspath(file_path)
    rel_path = os.path.relpath(abs_path, repo_path) if repo_path else abs_path
    rel_lower = rel_path.replace("\\", "/").lower()
    base_name = os.path.basename(abs_path).lower()
    path_parts = {part.lower() for part in rel_path.replace("\\", "/").split("/")}

    if path_parts & SKIP_DIR_NAMES:
        return True

    if base_name in SKIP_FILE_NAMES:
        return True

    if any(rel_lower.endswith(suffix) for suffix in SKIP_SUFFIXES):
        return True

    try:
        if os.path.getsize(abs_path) > max_file_bytes:
            return True
    except OSError:
        return True

    return _looks_generated(abs_path)


def _looks_generated(file_path: str) -> bool:
    """Cheap generated-file detection using a small header read."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as handle:
            header = handle.read(2048).lower()
    except OSError:
        return True

    return any(marker in header for marker in GENERATED_MARKERS)


def get_repo_head_info(repo_path: str):
    """Get the latest commit SHA, message, and date for the repository HEAD."""
    try:
        repo = Repo(repo_path)
        commit = repo.head.commit
        try:
            dt = commit.committed_datetime.astimezone(timezone.utc).isoformat()
        except Exception:
            dt = None
        return commit.hexsha[:7], commit.message.strip().split("\n")[0], dt
    except Exception:
        return "unknown", "No commit message found", None


def list_repo_files(repo_path: str, extensions: tuple):
    """Iterate over files in repository matching specified extensions."""
    normalized_exts = tuple(ext.lower() for ext in extensions)

    git_candidates = list(_iter_git_files(repo_path))
    if git_candidates:
        for file_path in git_candidates:
            if file_path.lower().endswith(normalized_exts) and not should_skip(file_path, repo_path):
                yield file_path
        return

    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d.lower() not in SKIP_DIR_NAMES]
        for file_name in files:
            file_path = os.path.join(root, file_name)
            if file_path.lower().endswith(normalized_exts) and not should_skip(file_path, repo_path):
                yield file_path


def _iter_git_files(repo_path: str) -> Iterable[str]:
    """Yield git-aware file candidates while respecting .gitignore."""
    try:
        repo = Repo(repo_path)
        output = repo.git.ls_files("--cached", "--others", "--exclude-standard", "-z")
    except Exception:
        return []

    if not output:
        return []

    return [
        os.path.join(repo_path, rel_path)
        for rel_path in output.split("\0")
        if rel_path
    ]


def get_commit_info(repo_path: str, file_path: str):
    """Get commit SHA, message, and date for a file."""
    try:
        repo = Repo(repo_path)
        rel = os.path.relpath(file_path, repo_path)
        commit = next(repo.iter_commits(paths=rel, max_count=1))
        try:
            dt = commit.committed_datetime.astimezone(timezone.utc).isoformat()
        except Exception:
            dt = None
        return commit.hexsha[:7], commit.message.strip().split("\n")[0], dt
    except Exception:
        return "unknown", "No commit message found", None
